project_id = "yggxugnbhxxoofskhjmv"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-payment-history]
verify_jwt = false

[functions.ai-assist]
verify_jwt = false
